# This file is generated by the kemory release-cli workflow. Do not edit by hand.
class Kemory < Formula
  desc "Persistent memory CLI for AI agents — browser sign-in, MCP bridge"
  homepage "https://github.com/SeKondBrainAILabs/kemory"
  version "0.4.2"
  license "MIT"

  # Apple Silicon only (see release workflow: no Intel macOS runner /
  # no universal2). Intel-Mac users install via pipx.
  on_macos do
    on_arm do
      url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/cli-v0.4.2/kemory-macos-arm64.tar.gz"
      sha256 "42b3ef96588cc2bd6a408ebca7437c6778a622275a6f934bf33a07c2b941f6fa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/cli-v0.4.2/kemory-linux-arm64.tar.gz"
      sha256 "a3a5631bad6cc84f6aa093334e7809af2a33b373e623db4c71bb4dad9c6f8da0"
    end
    on_intel do
      url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/cli-v0.4.2/kemory-linux-x64.tar.gz"
      sha256 "5cb661e38d9cf778f01ae6721536c8b1737e778006aefcda0904e65770355a5d"
    end
  end

  livecheck do
    url "https://github.com/SeKondBrainAILabs/homebrew-s9n"
    strategy :github_latest
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"kemory"
  end

  test do
    assert_match "version", shell_output("#{bin}/kemory --version")
  end
end
