# This file is generated by the kemory release-cli workflow. Do not edit by hand.
class Kemory < Formula
  desc "Persistent memory CLI for AI agents — browser sign-in, MCP bridge"
  homepage "https://github.com/SeKondBrainAILabs/kemory"
  version "0.6.1"
  license "MIT"

  # Apple Silicon only (see release workflow: no Intel macOS runner /
  # no universal2). Intel-Mac users install via pipx.
  on_macos do
    on_arm do
      url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/cli-v0.6.1/kemory-macos-arm64.tar.gz"
      sha256 "46dc8078089e03d75e9ca9545abcd9419e60d2c893a203b029a39a6f2c45c8bb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/cli-v0.6.1/kemory-linux-arm64.tar.gz"
      sha256 "cb0b77d2054a0119e881e91aa9d546f8c3a683033283e6a1ad1cb61964d1c17f"
    end
    on_intel do
      url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/cli-v0.6.1/kemory-linux-x64.tar.gz"
      sha256 "5912346809dd291f04caebea6cb8c111e16c31af76a3b6101324b113e924cfc4"
    end
  end

  livecheck do
    url "https://github.com/SeKondBrainAILabs/homebrew-s9n"
    strategy :github_latest
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"kemory"

    # Shell completions. Generated by running the freshly-installed
    # binary, so they always match the commands this build actually
    # has — a checked-in copy would drift the moment one is added.
    generate_completions_from_executable(
      libexec/"kemory", "completion", shell_parameter_format: :arg
    )
  end

  test do
    assert_match "version", shell_output("#{bin}/kemory --version")
    # Proves the [tui] extra survived the freeze: the browse
    # command only exists when kemory_cli.tui imports, which is
    # what breaks in a binary missing textual .tcss data files.
    # No credentials in the brew sandbox, so this exits non-zero
    # either way — what differs is WHICH failure. "log in first"
    # means the tui import succeeded; the install hint means the
    # extra did not survive the freeze.
    refute_match "optional TUI dependency",
                 shell_output("#{bin}/kemory browse 2>&1", 3)
  end
end
