# This file is generated by the release workflow. Do not edit by hand.
class S9n < Formula
  desc "Connect coding agents to SeKondBrain (MCP) via browser sign-in"
  homepage "https://www.sekondbrain.ai"
  version "0.1.2"
  license "MIT"

  # Single universal2 build serves both Apple Silicon and Intel.
  on_macos do
    url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/v0.1.2/s9n-macos-universal.tar.gz"
    sha256 "dced34ad49b4b2f929e0f28714b684b806de7ec2eadf7736e5962ef1a5fd17b2"
  end

  on_linux do
    on_arm do
      url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/v0.1.2/s9n-linux-arm64.tar.gz"
      sha256 "99c2161a0406241baf7fc4b6d3b2eed48c3f50564bf2089b8aa3bd8582f35fba"
    end
    on_intel do
      url "https://github.com/SeKondBrainAILabs/homebrew-s9n/releases/download/v0.1.2/s9n-linux-x64.tar.gz"
      sha256 "8d4b4541e56d347e8f8fe9181d8b60222388144a8ba05ff45a643efef6bc805f"
    end
  end

  livecheck do
    url "https://github.com/SeKondBrainAILabs/homebrew-s9n"
    strategy :github_latest
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"s9n"
  end

  test do
    assert_match "version", shell_output("#{bin}/s9n --version")
  end
end
